version: '3.7'
services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    hostname: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - BASE_URL=http://localhost:80
      - INSTANCE_NAME=homenetwork.co.in
  web:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - ./letsencrypt:/etc/letsencrypt